apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: payflow-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secrets
            key: secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payflow-secrets
  namespace: payflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payflow-secrets-manager
    kind: ClusterSecretStore
  target:
    name: payflow-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: payflow/production
        property: jwt-secret
    - secretKey: DB_PASSWORD
      remoteRef:
        key: payflow/production
        property: db-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: payflow/production
        property: redis-password
    - secretKey: GATEWAY_INTERNAL_SECRET
      remoteRef:
        key: payflow/production
        property: gateway-secret
    - secretKey: INTERNAL_SERVICE_SIGNING_SECRET
      remoteRef:
        key: payflow/production
        property: service-signing-secret
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: payflow/production
        property: stripe-webhook-secret
    - secretKey: RAZORPAY_WEBHOOK_SECRET
      remoteRef:
        key: payflow/production
        property: razorpay-webhook-secret