apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payflow

resources:
  - namespace.yml
  - services/
  - ingress.yml

commonLabels:
  app.kubernetes.io/name: payflow
  app.kubernetes.io/part-of: payflow