apiVersion: v1
kind: Secret
metadata:
  name: payflow-secrets
  namespace: payflow
type: Opaque
stringData:
  JWT_SECRET: ""
  GATEWAY_INTERNAL_SECRET: ""
  REDIS_PASSWORD: ""
  DB_USERNAME: payflow
  DB_PASSWORD: ""
  RAZORPAY_WEBHOOK_SECRET: ""
  STRIPE_WEBHOOK_SECRET: ""
  STRIPE_SIGNING_SECRET: ""
  PAYPAL_WEBHOOK_ID: ""
  WEBHOOK_SIGNATURE_SECRET: ""
  INTERNAL_SERVICE_SIGNING_SECRET: ""