spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/payflow
    password: payflow_dev_pass_123
  kafka:
    bootstrap-servers: kafka:9092
